### PR TITLE
Tell rollup-plugin-babel not to parse JSON files

### PR DESCRIPTION
**Pull request by jonataswalker**
See https://github.com/rollup/rollup-plugin-babel/issues/48

### CODE REVIEW

**Comment by eventualbuddha** [comment]
@rollup/collaborators what should we do with this? Seems like we should just make it work properly by default if possible.

**Comment by TrySound** [comment]
I just think about it. Maybe we should specify defaults `include` as `**/*.js`?

**Comment by TrySound** [comment]
Hm.. maybe even `**/*.{js,mjs}`

**Comment by Victorystick** [comment]
Why not have a default exclude for `**/*.json`?

**Comment by TrySound** [comment]
@Victorystick Because can be not only `json`. Blacklist is useless here.

**Comment by Victorystick** [comment]
@TrySound should we instead opt for the defaults used by Babel itself?

According to [Babel's website](https://babeljs.io/docs/usage/require/):
> 
All subsequent files required by node with the extensions `.es6`, `.es`, `.jsx` and `.js` will be transformed by Babel.

So `**/*.{es6|es|jsx|js}`?

**Comment by TrySound** [comment]
Yep. What about `.mjs`?

**Comment by Victorystick** [comment]
@TrySound With the [unambiguous JavaScript grammar proposal](https://github.com/bmeck/UnambiguousJavaScriptGrammar) having been accepted, we probably won't be seing any `.mjs` files.

**Comment by TrySound** [comment]
Okay. I don't think es, es6 and jsx are valid extensions. Let's just use js.

**Comment by Rich-Harris** [comment]
Going to close this in favour of https://github.com/rollup/rollup-plugin-babel/issues/111, as this is better fixed in that plugin than this one

**Pull request closed without merging**
