### PR TITLE
trim leading space if there are no namedExports.

### PR DESCRIPTION
**Pull request by btakita**
Fixes https://github.com/rollup/rollup-plugin-json/issues/19

### CODE REVIEW

**Comment by kzc** [comment]
Rather than using `.trim()` which would shift all the AST offsets referring to `code`, I'd suggest setting `defaultExportNode.start` to the correct value. It appears to be an off by one error?

If the fix in https://github.com/rollup/rollup/issues/1146#issuecomment-266943697 works then this PR wouldn't needed - although it'd be technically more correct.

**Comment by kzc** [comment]
See also: rollup/rollup#1146

**Comment by kzc** [comment]
See also: https://github.com/rollup/rollup/pull/1152

**Comment by Rich-Harris** [comment]
Thanks – I figured there's no harm fixing the bug in both places

**Pull request merged**
